version: "3.8"
services:
  app:
    container_name: app
    build:
      context: .
      network: host

    ports:
      - "8080:8080"
    networks:
      - local-network

networks:
  local-network:
    driver: bridge